# Generated by Django 4.2.4 on 2023-09-01 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Количество ингредиентов должно быть не менее 1'), django.core.validators.MaxValueValidator(10000, 'Количество ингредиентов должно быть не более 10000')], verbose_name='Количество ингредиента'),
        ),
    ]
