# Generated by Django 4.2.4 on 2023-09-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Загрузите картинку', upload_to='recipes/', verbose_name='Картинка'),
        ),
    ]
